### ISSUE TITLE
Preprocessing

### ISSUE THREAD

**Issue by akhanss** [ngessert/isic2019#2]
Hi
Thank you for a great repo, and congratulations on winning the competition. I read your manuscript, however, I can't find the code snippet of preprocessing (**cropping the relevant field of view of an image and color constancy**). Could you please help me how to do these preprocessing actually. 

Regards,
Azam.

**Comment by ngessert** [comment]
Hi Azam, the preprocessing part is in Matlab, I added the scripts for that.
