### ISSUE TITLE
Balanced Multiclass Accuracy

### ISSUE THREAD

**Issue by LezardValeth97** [ngessert/isic2019#3]
Sorry to create a new issue since you haven't responsed to the last issue, I was really confuse about the metric called Balanced Multiclass Accuracy, I read the definition but didn't know for sure what is it and how to calculate it, Could you help me answer these question? 

Thank you very much!

**Comment by ngessert** [comment]
Hi, sorry for the late response, cleaning up old issues. The balanced multi class accuracy is just a multi-class sensitivity (TP / (TP + FN)), averaged across classes.
