### ISSUE TITLE
KeyError: 'input_size_load'

### ISSUE THREAD

**Issue by MariaARicci** [ngessert/isic2019#4]
Hi there, thanks for sharing your script. I am having some trouble with _eval.py_, as it seems **mdlParams['input_size_load']** has neither been defined nor has a value been assigned to it. What does this stands for ? Could you help me please?

**Comment by ngessert** [comment]
Hi, sorry for the late response, I am cleaning up old issues. That key is unused, you should be able to remove it without consequences.

**Comment by sanjib-repo** [comment]
Given eval.py has references to input_size_load so either update eval.py and replace all references of input_size_load with input_size (which is defined in the configuration file under cfg/2019 folder) or define mdlParams['input_size_load'] = mdlParams['input_size'] in the configuration file.
