### ISSUE TITLE
Missing 2019 csv file and data set

### ISSUE THREAD

**Issue by lebe1** [ngessert/isic2019#5]
Dear Nils,

I'm trying to recreate your project for my bachelorthesis to have a running machine learning classifier algorithm to compare it to an active learning classifier algorithm. Sadly I cannot get any data from 2019 via this [link](https://challenge2019.isic-archive.com/data.html). So I had to download datasets for the 2020 challenge and delete additional columns and afterwards one-hot encode it. I assume something is wrong with my csv file i.e. are the only columns 'image', 'sex', 'age_approx', 'anatom_site_general_challenge' and 'diagnosis' ? 

I would really appreciate to receive an answer.

With kind regards,

Leon

**Comment by ngessert** [comment]
Hi, sorry for the late response, I am cleaning up old issues. The 2020 data indeed has a different format, there aren't specific lesion types provided for all images. You can find all data (including the 2019 data) in the isic archive.
